version: '3'

services:
    dev-service:
        build: .
        volumes:
            - ./src:/usr/src/app/src
        ports:
            - 80:3000
        environment:
            - CHOKIDAR_USEPOLLING=true