# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: git Actions
        uses: srt32/git-actions@v0.0.3

      - name: Install dependencies
        run: npm install

      # Runs a single command using the runners shell
      - name: Build the project
        run: npm run build
        
      # Runs a set of commands using the runners shell
      - name: Uploud to the branch prod
        run: |
          cd build
          git config --global user.name "GitHub Bot"
          git config --global user.email "noreply@github.com"
          git init
          git add .
          git commit -m "Auto deploy from GitHub Actions build $GITHUB_RUN_NUMBER"
          git remote add origin https://${{ secrets.GIT_TOKEN }}@github.com/israelyago/chefio-webapp.git
          git push --force origin master:prod
